import Footer from "@/componets/Footer";
import "./globals.css";
import Navbar from "@/componets/Navbar";
import { Urbanist } from 'next/font/google';


const urbanistFont = Urbanist({
  
  subsets: ["latin"],
});



export const metadata = {
  title: "pixgen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${urbanistFont.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
